[uni] update docker-deploy.yml

diff --git a/.github/workflows/docker-deploy.yml b/.github/workflows/docker-deploy.yml
--- a/.github/workflows/docker-deploy.yml
+++ b/.github/workflows/docker-deploy.yml
@@ -41,10 +41,12 @@ jobs:
           echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
           ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts
+          
+      # Step: 6.5    
       - name: Remove old archive file
         run: |
           ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} << 'EOF'
-            rm ~/docker-images/aplang-website.tar
+            [ -f ~/docker-images/aplang-website.tar ] && rm -f ~/docker-images/aplang-website.tar || echo "File not found, skipping removal"
           EOF
       # Step 7: Copy Docker image to remote server using SCP
       - name: SCP Docker Image to Server
